/*
 *      OpenEdge syntax highlighter
 *
 *      based on
 *      Pig Latin Mode for CodeMirror 2
 *      @author Prasanth Jayachandran
 *      @link   https://github.com/prasanthj/pig-codemirror-2
 *  This implementation is adapted from PL/SQL mode in CodeMirror 2.
 */
CodeMirror.defineMode("openedge", function(_config, parserConfig) {
    var keywords = parserConfig.keywords,
        builtins = parserConfig.builtins,
        types = parserConfig.types,
        multiLineStrings = parserConfig.multiLineStrings;

    var isOperatorChar = /[*+\%<>=&?:\/!|]/;

    function chain(stream, state, f) {
        state.tokenize = f;
        return f(stream, state);
    }

    var type;
    function ret(tp, style) {
        type = tp;
        return style;
    }

    function tokenComment(stream, state) {
        var isEnd = false;
        var ch;
        while(ch = stream.next()) {
            if(ch == "/" && isEnd) {
                state.tokenize = tokenBase;
                break;
            }
            isEnd = (ch == "*");
        }
        return ret("comment", "comment");
    }

    function tokenString(quote) {
        return function(stream, state) {
            var escaped = false, next, end = false;
            while((next = stream.next()) != null) {
                if (next == quote && !escaped) {
                    end = true; break;
                }
                escaped = !escaped && next == "\\";
            }
            if (end || !(escaped || multiLineStrings))
                state.tokenize = tokenBase;
            return ret("string", "error");
        };
    }

    function tokenBase(stream, state) {
        var ch = stream.next();

        // is a start of string?
        if (ch == '"' || ch == "'")
            return chain(stream, state, tokenString(ch));
        // is it one of the special chars
        //else if(/[\[\]{}\(\),;\.]/.test(ch))
        else if(/[\[\]{}\(\),;]/.test(ch))
            return ret(ch);
        // is it a number?
        else if(/\d/.test(ch)) {
            stream.eatWhile(/[\w\.]/);
            return ret("number", "number");
        }
        // multi line comment or operator
        else if (ch == "/") {
            if (stream.eat("*")) {
                return chain(stream, state, tokenComment);
            }
            else {
                stream.eatWhile(isOperatorChar);
                return ret("operator", "operator");
            }
        }
        // single line comment or operator
        /*
        else if (ch=="-") {
            if(stream.eat("-")){
                stream.skipToEnd();
                return ret("comment", "comment");
            }
            else {
                stream.eatWhile(isOperatorChar);
                return ret("operator", "operator");
            }
        } */
        // is it an operator
        else if (isOperatorChar.test(ch)) {
            stream.eatWhile(isOperatorChar);
            return ret("operator", "operator");
        }
        else {
            // get the while word
            stream.eatWhile(/[\w\$_]/);
            // is it one of the listed keywords?
            if (keywords && keywords.propertyIsEnumerable(stream.current().toUpperCase())) {
                //if (stream.eat(")") || stream.eat(".")) {
                if (stream.eat(")") ) {
                    //keywords can be used as variables like flatten(group), group.$0 etc..
                }
                else {
                    return ("keyword", "keyword");
                }
            }
            // is it one of the builtin functions?
            if (builtins && builtins.propertyIsEnumerable(stream.current().toUpperCase()))
            {
                return ("keyword", "variable-2");
            }
            // is it one of the listed types?
            if (types && types.propertyIsEnumerable(stream.current().toUpperCase()))
                return ("keyword", "variable-3");
            // default is a 'variable'
            return ret("variable", "pig-word");
        }
    }

    // Interface
    return {
        startState: function() {
            return {
                tokenize: tokenBase,
                startOfLine: true
            };
        },

        token: function(stream, state) {
            if(stream.eatSpace()) return null;
            var style = state.tokenize(stream, state);
            return style;
        }
    };
});

(function() {
    function keywords(str) {
        var obj = {}, words = str.split(" ");
        for (var i = 0; i < words.length; ++i) obj[words[i]] = true;
        return obj;
    }

    // builtin funcs taken from trunk revision 1303237
    /*var pBuiltins = "ABS ACOS ARITY ASIN ATAN AVG BAGSIZE BINSTORAGE BLOOM BUILDBLOOM CBRT CEIL "
        + "CONCAT COR COS COSH COUNT COUNT_STAR COV CONSTANTSIZE CUBEDIMENSIONS DIFF DISTINCT DOUBLEABS "
        + "DOUBLEAVG DOUBLEBASE DOUBLEMAX DOUBLEMIN DOUBLEROUND DOUBLESUM EXP FLOOR FLOATABS FLOATAVG "
        + "FLOATMAX FLOATMIN FLOATROUND FLOATSUM GENERICINVOKER INDEXOF INTABS INTAVG INTMAX INTMIN "
        + "INTSUM INVOKEFORDOUBLE INVOKEFORFLOAT INVOKEFORINT INVOKEFORLONG INVOKEFORSTRING INVOKER "
        + "ISEMPTY JSONLOADER JSONMETADATA JSONSTORAGE LAST_INDEX_OF LCFIRST LOG LOG10 LOWER LONGABS "
        + "LONGAVG LONGMAX LONGMIN LONGSUM MAX MIN MAPSIZE MONITOREDUDF NONDETERMINISTIC OUTPUTSCHEMA  "
        + "PIGSTORAGE PIGSTREAMING RANDOM REGEX_EXTRACT REGEX_EXTRACT_ALL REPLACE ROUND SIN SINH SIZE "
        + "SQRT STRSPLIT SUBSTRING SUM STRINGCONCAT STRINGMAX STRINGMIN STRINGSIZE TAN TANH TOBAG "
        + "TOKENIZE TOMAP TOP TOTUPLE TRIM TEXTLOADER TUPLESIZE UCFIRST UPPER UTF8STORAGECONVERTER "; */
    var pBuiltins = "";
    
    // taken from QueryLexer.g
    var pKeywords = "ACCUM ACCUMULATE ACTIVE-WINDOW ADD ADVISE ALERT-BOX ALIAS ALL ANYWHERE APPEND "
    	+ "APPLY AS ASCENDING ASSIGN AT BEFORE-HIDE BELL BGCOLOR BREAK BROWSE BUFFER BUFFER-COMPARE "
    	+ "BUFFER-COPY BUTTON BUTTONS BY CACHE CALL CASE CDECL CHAR CHARACTER CHOOSE CLEAR CLIPBOARD "
    	+ "CLOSE COL COLON COLOR COLOR-TABLE COLUMN COM-HANDLE COM-SELF COMBO-BOX COMPILE COMPILER "
    	+ "CONNECT CONTROL-FRAME CREATE CURRENT-LANGUAGE CURRENT-VALUE CURRENT-WINDOW CURSOR DATABASE "
    	+ "DATE DDE DEBUG-LIST DEBUGGER DEC DECIMAL DEF DEFAULT-NOXLATE DEFAULT-WINDOW DEFINE DELETE "
    	+ "DESCENDING DIALOG-BOX DICT DICTIONARY DISABLE DISCONNECT DISP DISPLAY DO DOS DOWN DROP "
    	+ "DROP-DOWN-LIST DYN-FUNCTION EACH ECHO EDITING EDITOR ELSE ENABLE END END-ERROR ENDKEY "
    	+ "ENTRY ERROR ERROR-STATUS EVENTS EXCL EXCLUSIVE EXCLUSIVE-LOCK EXECUTE EXPORT EXTERNAL "
    	+ "FGCOLOR FIELD FIELD-GROUP FIELDS FILE-INFO FILE-INFORMATION FILL-IN FIND FIND-CASE-SENSITIVE "
    	+ "FIND-GLOBAL FIND-NEXT-OCCURRENCE FIND-PREV-OCCURRENCE FIND-SELECT FIND-WRAP-AROUND FOCUS "
    	+ "FONT FONT-TABLE FOR FORM FORMAT FRAME FRAME-VALUE FROM FROM-CHARS FROM-PIXELS FUNCT FUNCTION "
    	+ "GET GET-FILE GET-KEY-VALUE GLOBAL GO-ON HANDLE HIDE IF IMAGE IMPORT IN INDEX-FIELD INIT "
    	+ "INITIAL INITIATE INPUT INPUT-OUTPUT INSERT INT INTEGER JOIN KEEP-MESSAGES KEEP-TAB-ORDER "
    	+ "KEY-CODE KEY-FUNCTION KEY-LABEL LAST-EVENT LAST-KEY LEAVE LENGTH LIKE LITERAL LOAD LOAD-CONTROL "
    	+ "LOG LOGICAL MACHINE-CLASS MANDATORY MAP MEMPTR MENU MENU-ITEM MESSAGE MOUSE NEXT NEXT-PROMPT "
    	+ "NO-APPLY NO-ATTR NO-ATTR-SPACE NO-BOX NO-CONVERT NO-ECHO NO-ERROR NO-FILL NO-HELP NO-HIDE "
    	+ "NO-LABEL NO-LABELS NO-LOCK NO-MAP NO-PAUSE NO-PREFETCH NO-UNDERLINE NO-UNDO NO-VALIDATE "
    	+ "NO-WAIT OBJECT OF OLD ON OPEN ORDINAL OS-APPEND OS-COMMAND OS-COPY OS-CREATE-DIR OS-DELETE "
    	+ "OS-DIR OS-RENAME OS400 OTHERWISE OUTPUT OVERLAY PAGE PAGE-SIZE PAGED PARAMETER PASCAL PAUSE "
     	+ "PERSISTENT PIXELS PREPROCESS PRESELECT PRIMARY PRINTER-SETUP PRINTER PRIVATE PROCEDURE PROCESS "
     	+ "PROC-STATUS PROGRAM-NAME PROMPT PROMPT-FOR PROMSGS PROPATH PUBLISH PUT PUT-BYTE PUT-DOUBLE "
     	+ "PUT-FLOAT PUT-KEY-VALUE PUT-LONG PUT-SHORT PUT-STRING QUERY QUERY-TUNING QUIT RADIO-SET RAW "
     	+ "RAW-TRANSFER RCODE-INFO READKEY RECID RECTANGLE RELEASE RENAME REPEAT REPOSITION REQUEST "
     	+ "RETURN REVERT ROW ROWID RUN RUN-PROCEDURE SAVE SCREEN SCREEN-IO SCROLL SCROLLING SEEK "
     	+ "SELECTION-LIST SELF SEND SERVER SESSION SET SET-POINTER-VALUE SET-SIZE SHARE SHARE-LOCK "
     	+ "SHARED SHOW-STATS SILENT SIZE SLIDER SOURCE-PROCEDURE SRC STATUS STDCALL STOP STORED-PROCEDURE "
     	+ "STREAM STREAM-IO STRING-XREF SUB-MENU SUBSCRIBE SUBSTRING SUPER SYSTEM-DIALOG  SYSTEM-HELP "
     	+ "TABLE TARGET TARGET-PROCEDURE TEMP-TABLE TERM TERMINAL TERMINATE TEXT TEXT-CURSOR TEXT-SEG-GROWTH "
     	+ "THEN THIS-PROCEDURE THROUGH THRU TO TOGGLE-BOX TRANS TRIGGER TRIGGER TRIGGERS UNBUFFERED UNDERLINE "
     	+ "UNDO UNFORMATTED UNIQUE UNIX UNLESS-HIDDEN UNLOAD UP UPDATE USE USE-REVVIDE USE-REVVIDEO USE-UNDERLINE "
     	+ "V6FRAME VALIDATE VALUE VAR VARIABLE VIEW VIEW-AS WAIT-FOR WEB-CONTEXT WHEN WHERE WHILE WIDGET "
     	+ "WIDGET-HANDLE WIDGET-POOL WINDOW WINDOW-CLOSE WINDOW-MAXIMIZED WINDOW-MINIMIZED WINDOW-NORMAL "
     	+ "WITH WORK-TABLE WORKFILE WRITE "
     	+ "ABSOLUTE ACCUM ALIAS AMBIGUOUS AND ASC AVAILABLE BEGINS CAN-DO CAN-FIND CAN-QUERY CAN-SET CAPS CHR "
     	+ "CODEPAGE-CONVERT CONNECTED COUNT-OF CURRENT-CHANGED CURRENT-LANGUAGE CURRENT-RESULT-ROW CURRENT-VALUE "
     	+ "CURRENT_DATE DATASERVERS DATE DAY DBCODEPAGE DBCOLLATION DBNAME DBPARAM DBRESTRICTIONS DBTASKID "
     	+ "DBTYPE DBVERSION DECIMAL DYNAMIC-FUNCTION ENCODE ENTERED ENTRY EQ ETIME EXP EXTENT FALSE FILL FIRST "
     	+ "FIRST-OF FRAME-COL FRAME-DB FRAME-DOWN FRAME-FIELD FRAME-FILE FRAME-INDEX FRAME-LINE FRAME-NAME "
     	+ "FRAME-ROW FRAME-VALUE GATEWAYS GE GET-BYTE GET-CODEPAGES GET-COLLATIONS GET-DOUBLE GET-FLOAT "
     	+ "GET-LONG GET-POINTER-VALUE GET-SHORT GET-SIZE GET-STRING GET-UNSIGNED-SHORT GO-PENDING GT INDEX "
     	+ "INPUT INTEGER IS-ATTR-SPACE IS-LEAD-BYTE KBLABEL KEYCODE KEYFUNCTION KEYLABEL KEYWORD KEYWORD-ALL "
     	+ "LAST LAST-OF LASTKEY LC LDBNAME LE LEFT-TRIM LENGTH LIBRARY LINE-COUNTER LIST-EVENTS LIST-QUERY-ATTRS "
     	+ "LIST-SET-ATTRS LIST-WIDGETS LOAD-PICTURE LOCKED LOG LOOKUP LT MATCHES MAXIMUM MEMBER MESSAGE-LINES "
     	+ "MINIMUM MODULO MONTH NE NEW NEXT-VALUE NO NOT NUM-ALIASES NUM-DBS NUM-ENTRIES NUM-RESULTS OPSYS "
     	+ "OR OS-DRIVES OS-ERROR OS-GETENV PAGE-NUMBER PAGE-SIZE PDBNAME PROC-HANDLE PROC-STATUS PROGRAM-NAME "
     	+ "PROGRESS PROMSGS PROPATH PROVERSION QUERY-OFF-END R-INDEX RANDOM RAW RECID RECORD-LENGTH REPLACE "
     	+ "RETRY RETURN-VALUE RGB-VALUE RIGHT-TRIM ROUND ROWID SCREEN-LINES SDBNAME SEARCH SEEK SETUSERID "
     	+ "SKIP SPACE SQRT STRING SUBSTITUTE SUBSTRING TERMINAL TIME TO-ROWID TODAY TRANSACTION TRIM "
     	+ "TRUE TRUNCATE USERID VALID-EVENT VALID-HANDLE WEEKDAY WIDGET-HANDLE YEAR YES "
     	+ "ACCELERATOR ADM-DATA APPL-ALERT-BOXES ATTR-SPACE AUTO-END-KEY AUTO-GO AUTO-INDENT AUTO-RESIZE "
     	+ "AUTO-RETURN AUTO-ZAP AVAILABLE-FORMATS BACKGROUND BATCH-MODE BGCOLOR BLANK BLOCK-ITERATION-DISPLAY "
     	+ "BORDER-BOTTOM-CHARS BORDER-BOTTOM-PIXELS BORDER-LEFT-CHARS BORDER-LEFT-PIXELS BORDER-RIGHT-CHARS "
     	+ "BORDER-RIGHT-PIXELS BORDER-TOP-CHARS BORDER-TOP-PIXELS BOX BOX-SELECTABLE BUFFER-CHARS "
     	+ "BUFFER-LINES CANCEL-BUTTON CENTERED CHARSET CHECKED CODE CODEPAGE COLUMN COLUMN-BGCOLOR COLUMN-DCOLOR "
     	+ "COLUMN-FGCOLOR COLUMN-FONT COLUMN-PFCOLOR COLUMN-SCROLLING COM-HANDLE COMPONENT-HANDLE CONVERT-3D-COLORS "
     	+ "CPCASE CPCOLL CPINTERNAL CPLOG CPPRINT CPRCODEIN CPRCODEOUT CPSTREAM CPTERM CRC-VALUE CURRENT-COLUMN "
     	+ "CURRENT-ITERATION CURRENT-ROW-MODIFIED CURRENT-WINDOW CURSOR-CHAR CURSOR-LINE CURSOR-OFFSET DATA-ENTRY-RETURN "
     	+ "DATA-TYPE DATE-FORMAT DB-REFERENCES DBNAME DCOLOR DDE-ERROR DDE-ID DDE-ITEM DDE-NAME DDE-TOPIC DEBLANK "
     	+ "DEFAULT DEFAULT-BUTTON DELIMITER DISPLAY-TYPE DOWN DRAG-ENABLED DYNAMIC EDGE-CHARS EDGE-PIXELS EDIT-CAN-UNDO "
     	+ "EMPTY ERROR ERROR-COLUMN ERROR-ROW EVENT-TYPE EXPAND FGCOLOR FILE-NAME FILE-OFFSET FILE-TYPE FILLED "
     	+ "FIRST-CHILD FIRST-COLUMN FIRST-PROCEDURE FIRST-SERVER FIRST-TAB-ITEM FOCUSED-ROW FONT FOREGROUND FORMAT "
     	+ "FRAME FRAME-COL FRAME-NAME FRAME-ROW FRAME-SPACING FRAME-X FRAME-Y FREQUENCY FULL-HEIGHT-CHARS "
     	+ "FULL-HEIGHT-PIXELS FULL-PATHNAME FULL-WIDTH-CHARS FULL-WIDTH-PIXELS FUNCTION GRAPHIC-EDGE GRID-FACTOR-HORIZONTAL "
     	+ "GRID-FACTOR-VERTICAL GRID-SNAP GRID-UNIT-HEIGHT-CHARS GRID-UNIT-HEIGHT-PIXELS GRID-UNIT-WIDTH-CHARS "
     	+ "GRID-UNIT-WIDTH-PIXELS GRID-VISIBLE HANDLE HEIGHT HEIGHT-CHARS HEIGHT-PIXELS HELP HIDDEN HORIZONTAL HWND "
     	+ "IMMEDIATE-DISPLAY INDEX INNER-CHARS INNER-LINES INTERNAL-ENTRIES ITEMS-PER-ROW KEEP-FRAME-Z-ORDER LABEL "
     	+ "LABEL-BGCOLOR LABEL-DCOLOR LABEL-FGCOLOR LABEL-FONT LABELS LANGUAGES LARGE LARGE-TO-SMALL LAST-CHILD "
     	+ "LAST-PROCEDURE LAST-SERVER LAST-TAB-ITEM LEFT LENGTH LINE LIST-ITEMS LOG-ID MANUAL-HIGHLIGHT MAX-CHARS "
     	+ "MAX-DATA-GUESS MAX-HEIGHT MAX-HEIGHT-CHARS MAX-HEIGHT-PIXELS MAX-VALUE MAX-WIDTH MAX-WIDTH-CHARS MAX-WIDTH-PIXELS "
     	+ "MENU-BAR MENU-KEY MENU-MOUSE MESSAGE-AREA MESSAGE-AREA-FONT MIN-HEIGHT-CHARS MIN-HEIGHT-PIXELS MIN-VALUE "
     	+ "MIN-WIDTH-CHARS MIN-WIDTH-PIXELS MODIFIED MOVABLE MULTIPLE MULTITASKING-INTERVAL NAME NEW-ROW NEXT-COLUMN "
     	+ "NEXT-SIBLING NEXT-TAB-ITEM NO-CURRENT-VALUE NO-FOCUS NUM-BUTTONS NUM-COLUMNS NUM-ENTRIES NUM-FORMATS NUM-ITEMS "
     	+ "NUM-ITERATIONS NUM-LINES NUM-LOCKED-COLUMNS NUM-MESSAGES NUM-SELECTED-ROWS NUM-SELECTED-WIDGETS NUM-TABS "
     	+ "NUM-TO-RETAIN NUMERIC-FORMAT ON-FRAME-BORDER OVERLAY OWNER PAGE-BOTTOM PAGE-TOP PARAMETER PARENT PATHNAME "
     	+ "PERSISTENT PFCOLOR PIXELS-PER-COLUMN PIXELS-PER-ROW POPUP-MENU POPUP-ONLY PREV-COLUMN PREV-SIBLING PREV-TAB-ITEM "
     	+ "PRINTER-CONTROL-HANDLE PRINTER-NAME PRINTER-PORT PRIVATE-DATA PROGRESS-SOURCE PROXY RADIO-BUTTONS "
     	+ "RCODE-INFORMATION READ-ONLY REFRESHABLE REMOTE RESIZABLE RESIZE RETURN-INSERTED ROW ROW-MARKERS SCREEN-LINES "
     	+ "SCREEN-VALUE SCROLL-BARS SCROLLABLE SCROLLBAR-HORIZONTAL SCROLLBAR-VERTICAL SELECTABLE SELECTED SELECTION-END "
     	+ "SELECTION-START SELECTION-TEXT SENSITIVE SEPARATORS SERVER SIDE-LABEL-HANDLE SIDE-LABELS SORT STATUS-AREA "
     	+ "STATUS-AREA-FONT STOPPED STREAM SUBTYPE SUPPRESS-WARNINGS SYSTEM-ALERT-BOXES TAB-POSITION TABLE TEMP-DIRECTORY "
     	+ "TEXT-SELECTED THREE-D TIC-MARKS TIME-SOURCE TITLE TITLE-BGCOLOR TITLE-DCOLOR TITLE-FGCOLOR TITLE-FONT TOGGLE-BOX "
     	+ "TOOLTIP TOOLTIPS TOP TOP-ONLY TYPE UNIQUE-ID V6DISPLAY VALUE VIRTUAL-HEIGHT VIRTUAL-HEIGHT-CHARS "
     	+ "VIRTUAL-HEIGHT-PIXELS VIRTUAL-WIDTH VIRTUAL-WIDTH-CHARS VIRTUAL-WIDTH-PIXELS VISIBLE WARNING WIDGET-ENTER "
     	+ "WIDGET-HANDLE WIDGET-LEAVE WIDTH WIDTH-CHARS WIDTH-PIXELS WINDOW WINDOW-STATE WINDOW-SYSTEM WORD-WRAP "
     	+ "YEAR-OFFSET "
     	+ "ADD-EVENTS-PROCEDURE ADD-FIRST ADD-LAST CANCEL-BREAK CLEAR CLEAR-SELECTION CONNECT CONNECTED CONVERT-TO-OFFSET "
     	+ "CREATE-RESULT-LIST-ENTRY DEBUG DELETE DELETE-CHAR DELETE-CURRENT-ROW DELETE-LINE DELETE-SELECTED-ROW "
     	+ "DELETE-SELECTED-ROWS DESELECT-FOCUSED-ROW DESELECT-ROWS DESELECT-SELECTED-ROW DISABLE DISCONNECT DISPLAY-MESSAGE "
     	+ "EDIT-UNDO ENABLE ENTRY EXPORT FETCH-SELECTED-ROW GET-BLUE-VALUE GET-DYNAMIC GET-GREEN-VALUE GET-ITERATION "
     	+ "GET-MESSAGE GET-NUMBER GET-RED-VALUE GET-REPOSITIONED-ROW GET-RGB-VALUE GET-SELECTED-WIDGET GET-SIGNATURE "
     	+ "GET-TAB-ITEM GET-TEXT-HEIGHT-CHARS GET-TEXT-HEIGHT-PIXELS GET-TEXT-WIDTH-CHARS GET-TEXT-WIDTH-PIXELS "
     	+ "INITIATE INSERT INSERT-BACKTAB INSERT-FILE INSERT-ROW INSERT-STRING INSERT-TAB IS-ROW-SELECTED IS-SELECTED "
     	+ "LOAD-ICON LOAD-IMAGE LOAD-IMAGE-DOWN LOAD-IMAGE-INSENSITIVE LOAD-IMAGE-UP LOAD-MOUSE-POINTER LOAD-SMALL-ICON "
     	+ "LOADCONTROLS LOOKUP MOVE-AFTER-TAB-ITEM MOVE-BEFORE-TAB-ITEM MOVE-COLUMN MOVE-TO-BOTTOM MOVE-TO-EOF MOVE-TO-TOP "
     	+ "READ-FILE REFRESH REMOVE-EVENTS-PROCEDURE REPLACE REPLACE-SELECTION-TEXT SAVE-FILE SCROLL-TO-CURRENT-ROW "
        + "SCROLL-TO-ITEM SCROLL-TO-SELECTED-ROW SEARCH SELECT-FOCUSED-ROW SELECT-NEXT-ROW SELECT-PREV-ROW SELECT-ROW "
        + "SET-BLUE-VALUE SET-BREAK SET-DYNAMIC SET-GREEN-VALUE SET-RED-VALUE SET-REPOSITIONED-ROW SET-RGB-VALUE "
        + "SET-SELECTION SET-WAIT-STATE VALIDATE";

    // data types
    var pTypes = "END";
    //var pTypes = "BOOLEAN INT LONG FLOAT DOUBLE CHARARRAY BYTEARRAY BAG TUPLE MAP ";

    CodeMirror.defineMIME("progress", {
        name: "openedge",
        builtins: keywords(pBuiltins),
        keywords: keywords(pKeywords),
        types: keywords(pTypes)
    });
    
    CodeMirror.extendMode("openedge", {
          commentStart: "/*",
          commentEnd: "*/",
          newlineAfterToken: function(_type, content, textAfter, state) {
            return false;
          }
      });
  
}());
